version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.6
    commands:
      - echo "Installing dependencies..."
      - make install-aws
  build:
    commands:
      - echo "Running tests..."
      - make test
